/* =====================================================================
   Svetovni popotniki — seznam držav za kviz zastav
   200 držav iz Twinklovih kartic, slovenska imena, urejeno po abecedi.

   k  = koda zastave -> assets/zastave/<k>.svg
   sl = slovensko ime (to učenci povedo)
   en = angleško ime s kartic (za iskanje in primerjavo)
   c  = celina (za filtriranje naključnega izbora)
   ===================================================================== */
'use strict';

const DRZAVE = [
  { k:'af', sl:'Afganistan', en:'Afghanistan', c:'Azija' },
  { k:'al', sl:'Albanija', en:'Albania', c:'Evropa' },
  { k:'dz', sl:'Alžirija', en:'Algeria', c:'Afrika' },
  { k:'ad', sl:'Andora', en:'Andorra', c:'Evropa' },
  { k:'gb-eng', sl:'Anglija', en:'England', c:'Evropa' },
  { k:'ao', sl:'Angola', en:'Angola', c:'Afrika' },
  { k:'ag', sl:'Antigva in Barbuda', en:'Antigua and Barbuda', c:'Severna Amerika' },
  { k:'ar', sl:'Argentina', en:'Argentina', c:'Južna Amerika' },
  { k:'am', sl:'Armenija', en:'Armenia', c:'Azija' },
  { k:'aw', sl:'Aruba', en:'Aruba', c:'Severna Amerika' },
  { k:'au', sl:'Avstralija', en:'Australia', c:'Oceanija' },
  { k:'at', sl:'Avstrija', en:'Austria', c:'Evropa' },
  { k:'az', sl:'Azerbajdžan', en:'Azerbaijan', c:'Azija' },
  { k:'bs', sl:'Bahami', en:'Bahamas', c:'Severna Amerika' },
  { k:'bh', sl:'Bahrajn', en:'Bahrain', c:'Azija' },
  { k:'bd', sl:'Bangladeš', en:'Bangladesh', c:'Azija' },
  { k:'bb', sl:'Barbados', en:'Barbados', c:'Severna Amerika' },
  { k:'be', sl:'Belgija', en:'Belgium', c:'Evropa' },
  { k:'bz', sl:'Belize', en:'Belize', c:'Severna Amerika' },
  { k:'by', sl:'Belorusija', en:'Belarus', c:'Evropa' },
  { k:'bj', sl:'Benin', en:'Benin', c:'Afrika' },
  { k:'bw', sl:'Bocvana', en:'Botswana', c:'Afrika' },
  { k:'bg', sl:'Bolgarija', en:'Bulgaria', c:'Evropa' },
  { k:'bo', sl:'Bolivija', en:'Bolivia', c:'Južna Amerika' },
  { k:'ba', sl:'Bosna in Hercegovina', en:'Bosnia-Herzegovina', c:'Evropa' },
  { k:'br', sl:'Brazilija', en:'Brazil', c:'Južna Amerika' },
  { k:'bn', sl:'Brunej', en:'Brunei', c:'Azija' },
  { k:'bf', sl:'Burkina Faso', en:'Burkina Faso', c:'Afrika' },
  { k:'bi', sl:'Burundi', en:'Burundi', c:'Afrika' },
  { k:'bt', sl:'Butan', en:'Bhutan', c:'Azija' },
  { k:'cy', sl:'Ciper', en:'Cyprus', c:'Evropa' },
  { k:'ck', sl:'Cookovi otoki', en:'Cook Islands', c:'Oceanija' },
  { k:'cz', sl:'Češka', en:'Czechia', c:'Evropa' },
  { k:'cl', sl:'Čile', en:'Chile', c:'Južna Amerika' },
  { k:'me', sl:'Črna gora', en:'Montenegro', c:'Evropa' },
  { k:'dk', sl:'Danska', en:'Denmark', c:'Evropa' },
  { k:'cd', sl:'Demokratična republika Kongo', en:'Democratic Republic of Congo', c:'Afrika' },
  { k:'dm', sl:'Dominika', en:'Dominica', c:'Severna Amerika' },
  { k:'do', sl:'Dominikanska republika', en:'Dominican Republic', c:'Severna Amerika' },
  { k:'dj', sl:'Džibuti', en:'Djibouti', c:'Afrika' },
  { k:'eg', sl:'Egipt', en:'Egypt', c:'Afrika' },
  { k:'ec', sl:'Ekvador', en:'Ecuador', c:'Južna Amerika' },
  { k:'gq', sl:'Ekvatorialna Gvineja', en:'Equatorial Guinea', c:'Afrika' },
  { k:'ee', sl:'Estonija', en:'Estonia', c:'Evropa' },
  { k:'sz', sl:'Esvatini', en:'Eswatini', c:'Afrika' },
  { k:'et', sl:'Etiopija', en:'Ethiopia', c:'Afrika' },
  { k:'fj', sl:'Fidži', en:'Fiji', c:'Oceanija' },
  { k:'ph', sl:'Filipini', en:'Philippines', c:'Azija' },
  { k:'fi', sl:'Finska', en:'Finland', c:'Evropa' },
  { k:'fr', sl:'Francija', en:'France', c:'Evropa' },
  { k:'ga', sl:'Gabon', en:'Gabon', c:'Afrika' },
  { k:'gm', sl:'Gambija', en:'Gambia', c:'Afrika' },
  { k:'gh', sl:'Gana', en:'Ghana', c:'Afrika' },
  { k:'gr', sl:'Grčija', en:'Greece', c:'Evropa' },
  { k:'gd', sl:'Grenada', en:'Grenada', c:'Severna Amerika' },
  { k:'ge', sl:'Gruzija', en:'Georgia', c:'Azija' },
  { k:'gg', sl:'Guernsey', en:'Guernsey', c:'Evropa' },
  { k:'gy', sl:'Gvajana', en:'Guyana', c:'Južna Amerika' },
  { k:'gt', sl:'Gvatemala', en:'Guatemala', c:'Severna Amerika' },
  { k:'gn', sl:'Gvineja', en:'Guinea', c:'Afrika' },
  { k:'ht', sl:'Haiti', en:'Haiti', c:'Severna Amerika' },
  { k:'hn', sl:'Honduras', en:'Honduras', c:'Severna Amerika' },
  { k:'hr', sl:'Hrvaška', en:'Croatia', c:'Evropa' },
  { k:'in', sl:'Indija', en:'India', c:'Azija' },
  { k:'id', sl:'Indonezija', en:'Indonesia', c:'Azija' },
  { k:'iq', sl:'Irak', en:'Iraq', c:'Azija' },
  { k:'ir', sl:'Iran', en:'Iran', c:'Azija' },
  { k:'ie', sl:'Irska', en:'Republic of Ireland', c:'Evropa' },
  { k:'is', sl:'Islandija', en:'Iceland', c:'Evropa' },
  { k:'it', sl:'Italija', en:'Italy', c:'Evropa' },
  { k:'il', sl:'Izrael', en:'Israel', c:'Azija' },
  { k:'jm', sl:'Jamajka', en:'Jamaica', c:'Severna Amerika' },
  { k:'jp', sl:'Japonska', en:'Japan', c:'Azija' },
  { k:'ye', sl:'Jemen', en:'Yemen', c:'Azija' },
  { k:'jo', sl:'Jordanija', en:'Jordan', c:'Azija' },
  { k:'za', sl:'Južna Afrika', en:'South Africa', c:'Afrika' },
  { k:'kr', sl:'Južna Koreja', en:'South Korea', c:'Azija' },
  { k:'ss', sl:'Južni Sudan', en:'South Sudan', c:'Afrika' },
  { k:'kh', sl:'Kambodža', en:'Cambodia', c:'Azija' },
  { k:'cm', sl:'Kamerun', en:'Cameroon', c:'Afrika' },
  { k:'ca', sl:'Kanada', en:'Canada', c:'Severna Amerika' },
  { k:'ic', sl:'Kanarski otoki', en:'Canary Islands', c:'Afrika' },
  { k:'qa', sl:'Katar', en:'Qatar', c:'Azija' },
  { k:'kz', sl:'Kazahstan', en:'Kazakhstan', c:'Azija' },
  { k:'ke', sl:'Kenija', en:'Kenya', c:'Afrika' },
  { k:'kg', sl:'Kirgizistan', en:'Kyrgyzstan', c:'Azija' },
  { k:'ki', sl:'Kiribati', en:'Kiribati', c:'Oceanija' },
  { k:'cn', sl:'Kitajska', en:'China', c:'Azija' },
  { k:'co', sl:'Kolumbija', en:'Colombia', c:'Južna Amerika' },
  { k:'km', sl:'Komori', en:'Comoros', c:'Afrika' },
  { k:'xk', sl:'Kosovo', en:'Kosovo', c:'Evropa' },
  { k:'cr', sl:'Kostarika', en:'Costa Rica', c:'Severna Amerika' },
  { k:'cu', sl:'Kuba', en:'Cuba', c:'Severna Amerika' },
  { k:'kurd', sl:'Kurdistan', en:'Kurdistan', c:'Azija' },
  { k:'kw', sl:'Kuvajt', en:'Kuwait', c:'Azija' },
  { k:'la', sl:'Laos', en:'Laos', c:'Azija' },
  { k:'lv', sl:'Latvija', en:'Latvia', c:'Evropa' },
  { k:'ls', sl:'Lesoto', en:'Lesotho', c:'Afrika' },
  { k:'lb', sl:'Libanon', en:'Lebanon', c:'Azija' },
  { k:'lr', sl:'Liberija', en:'Liberia', c:'Afrika' },
  { k:'ly', sl:'Libija', en:'Libya', c:'Afrika' },
  { k:'li', sl:'Lihtenštajn', en:'Liechtenstein', c:'Evropa' },
  { k:'lt', sl:'Litva', en:'Lithuania', c:'Evropa' },
  { k:'lu', sl:'Luksemburg', en:'Luxembourg', c:'Evropa' },
  { k:'mg', sl:'Madagaskar', en:'Madagascar', c:'Afrika' },
  { k:'hu', sl:'Madžarska', en:'Hungary', c:'Evropa' },
  { k:'mw', sl:'Malavi', en:'Malawi', c:'Afrika' },
  { k:'mv', sl:'Maldivi', en:'Maldives', c:'Azija' },
  { k:'my', sl:'Malezija', en:'Malaysia', c:'Azija' },
  { k:'ml', sl:'Mali', en:'Mali', c:'Afrika' },
  { k:'mt', sl:'Malta', en:'Malta', c:'Evropa' },
  { k:'ma', sl:'Maroko', en:'Morocco', c:'Afrika' },
  { k:'mh', sl:'Marshallovi otoki', en:'Marshall Islands', c:'Oceanija' },
  { k:'mu', sl:'Mauritius', en:'Mauritius', c:'Afrika' },
  { k:'mx', sl:'Mehika', en:'Mexico', c:'Severna Amerika' },
  { k:'fm', sl:'Mikronezija', en:'Micronesia', c:'Oceanija' },
  { k:'mm', sl:'Mjanmar', en:'Myanmar', c:'Azija' },
  { k:'md', sl:'Moldavija', en:'Moldova', c:'Evropa' },
  { k:'mc', sl:'Monako', en:'Monaco', c:'Evropa' },
  { k:'mn', sl:'Mongolija', en:'Mongolia', c:'Azija' },
  { k:'mz', sl:'Mozambik', en:'Mozambique', c:'Afrika' },
  { k:'na', sl:'Namibija', en:'Namibia', c:'Afrika' },
  { k:'nr', sl:'Nauru', en:'Nauru', c:'Oceanija' },
  { k:'de', sl:'Nemčija', en:'Germany', c:'Evropa' },
  { k:'np', sl:'Nepal', en:'Nepal', c:'Azija' },
  { k:'ne', sl:'Niger', en:'Niger', c:'Afrika' },
  { k:'ng', sl:'Nigerija', en:'Nigeria', c:'Afrika' },
  { k:'ni', sl:'Nikaragva', en:'Nicaragua', c:'Severna Amerika' },
  { k:'nu', sl:'Niue', en:'Niue', c:'Oceanija' },
  { k:'nl', sl:'Nizozemska', en:'Netherlands', c:'Evropa' },
  { k:'no', sl:'Norveška', en:'Norway', c:'Evropa' },
  { k:'nz', sl:'Nova Zelandija', en:'New Zealand', c:'Oceanija' },
  { k:'om', sl:'Oman', en:'Oman', c:'Azija' },
  { k:'pk', sl:'Pakistan', en:'Pakistan', c:'Azija' },
  { k:'pw', sl:'Palau', en:'Palau', c:'Oceanija' },
  { k:'ps', sl:'Palestina', en:'State of Palestine', c:'Azija' },
  { k:'pa', sl:'Panama', en:'Panama', c:'Severna Amerika' },
  { k:'pg', sl:'Papua Nova Gvineja', en:'Papua New Guinea', c:'Oceanija' },
  { k:'py', sl:'Paragvaj', en:'Paraguay', c:'Južna Amerika' },
  { k:'pe', sl:'Peru', en:'Peru', c:'Južna Amerika' },
  { k:'pl', sl:'Poljska', en:'Poland', c:'Evropa' },
  { k:'pr', sl:'Portoriko', en:'Puerto Rico', c:'Severna Amerika' },
  { k:'pt', sl:'Portugalska', en:'Portugal', c:'Evropa' },
  { k:'ro', sl:'Romunija', en:'Romania', c:'Evropa' },
  { k:'rw', sl:'Ruanda', en:'Rwanda', c:'Afrika' },
  { k:'ru', sl:'Rusija', en:'Russia', c:'Evropa' },
  { k:'sb', sl:'Salomonovi otoki', en:'Solomon Islands', c:'Oceanija' },
  { k:'sv', sl:'Salvador', en:'El Salvador', c:'Severna Amerika' },
  { k:'ws', sl:'Samoa', en:'Samoa', c:'Oceanija' },
  { k:'sm', sl:'San Marino', en:'San Marino', c:'Evropa' },
  { k:'st', sl:'São Tomé in Príncipe', en:'São Tomé and Príncipe', c:'Afrika' },
  { k:'sa', sl:'Saudova Arabija', en:'Saudi Arabia', c:'Azija' },
  { k:'sc', sl:'Sejšeli', en:'Seychelles', c:'Afrika' },
  { k:'sn', sl:'Senegal', en:'Senegal', c:'Afrika' },
  { k:'gb-nir', sl:'Severna Irska', en:'Northern Ireland', c:'Evropa' },
  { k:'kp', sl:'Severna Koreja', en:'North Korea', c:'Azija' },
  { k:'mk', sl:'Severna Makedonija', en:'North Macedonia', c:'Evropa' },
  { k:'sl', sl:'Sierra Leone', en:'Sierra Leone', c:'Afrika' },
  { k:'sg', sl:'Singapur', en:'Singapore', c:'Azija' },
  { k:'sy', sl:'Sirija', en:'Syria', c:'Azija' },
  { k:'ci', sl:'Slonokoščena obala', en:'Ivory Coast', c:'Afrika' },
  { k:'sk', sl:'Slovaška', en:'Slovakia', c:'Evropa' },
  { k:'si', sl:'Slovenija', en:'Slovenia', c:'Evropa' },
  { k:'so', sl:'Somalija', en:'Somalia', c:'Afrika' },
  { k:'rs', sl:'Srbija', en:'Serbia', c:'Evropa' },
  { k:'cf', sl:'Srednjeafriška republika', en:'Central African Republic', c:'Afrika' },
  { k:'sr', sl:'Surinam', en:'Suriname', c:'Južna Amerika' },
  { k:'lc', sl:'Sveta Lucija', en:'Saint Lucia', c:'Severna Amerika' },
  { k:'kn', sl:'Sveti Krištof in Nevis', en:'Saint Kitts and Nevis', c:'Severna Amerika' },
  { k:'vc', sl:'Sveti Vincencij in Grenadine', en:'Saint Vincent and the Grenadines', c:'Severna Amerika' },
  { k:'gb-sct', sl:'Škotska', en:'Scotland', c:'Evropa' },
  { k:'es', sl:'Španija', en:'Spain', c:'Evropa' },
  { k:'lk', sl:'Šrilanka', en:'Sri Lanka', c:'Azija' },
  { k:'se', sl:'Švedska', en:'Sweden', c:'Evropa' },
  { k:'ch', sl:'Švica', en:'Switzerland', c:'Evropa' },
  { k:'tj', sl:'Tadžikistan', en:'Tajikistan', c:'Azija' },
  { k:'th', sl:'Tajska', en:'Thailand', c:'Azija' },
  { k:'tz', sl:'Tanzanija', en:'Tanzania', c:'Afrika' },
  { k:'tg', sl:'Togo', en:'Togo', c:'Afrika' },
  { k:'to', sl:'Tonga', en:'Tonga', c:'Oceanija' },
  { k:'tt', sl:'Trinidad in Tobago', en:'Trinidad and Tobago', c:'Severna Amerika' },
  { k:'tn', sl:'Tunizija', en:'Tunisia', c:'Afrika' },
  { k:'tr', sl:'Turčija', en:'Türkiye', c:'Azija' },
  { k:'tm', sl:'Turkmenistan', en:'Turkmenistan', c:'Azija' },
  { k:'tv', sl:'Tuvalu', en:'Tuvalu', c:'Oceanija' },
  { k:'ug', sl:'Uganda', en:'Uganda', c:'Afrika' },
  { k:'ua', sl:'Ukrajina', en:'Ukraine', c:'Evropa' },
  { k:'uy', sl:'Urugvaj', en:'Uruguay', c:'Južna Amerika' },
  { k:'uz', sl:'Uzbekistan', en:'Uzbekistan', c:'Azija' },
  { k:'vu', sl:'Vanuatu', en:'Vanuatu', c:'Oceanija' },
  { k:'va', sl:'Vatikan', en:'Vatican City', c:'Evropa' },
  { k:'ve', sl:'Venezuela', en:'Venezuela', c:'Južna Amerika' },
  { k:'vn', sl:'Vietnam', en:'Vietnam', c:'Azija' },
  { k:'tl', sl:'Vzhodni Timor', en:'East Timor', c:'Azija' },
  { k:'gb-wls', sl:'Wales', en:'Wales', c:'Evropa' },
  { k:'zm', sl:'Zambija', en:'Zambia', c:'Afrika' },
  { k:'us', sl:'Združene države Amerike', en:'USA', c:'Severna Amerika' },
  { k:'ae', sl:'Združeni arabski emirati', en:'United Arab Emirates', c:'Azija' },
  { k:'gb', sl:'Združeno kraljestvo', en:'United Kingdom', c:'Evropa' },
  { k:'zw', sl:'Zimbabve', en:'Zimbabwe', c:'Afrika' },
];

/** Celine v vrstnem redu, kot jih hočemo v spustnem meniju. */
const CELINE = ['Evropa', 'Azija', 'Afrika', 'Severna Amerika', 'Južna Amerika', 'Oceanija'];
